In [ ]:
import numpy as np

# Problem - 1: Array Creation:

empty_arr = np.empty((2, 2))
print("Empty 2x2 array:", empty_arr)


# 2
one_arr = np.ones((4,2))
print("one_array =",one_arr)

# 3
full_arr = np.full((4,4), fill_value =6)
print("Full_arr with fill value = ",full_arr)

# 4
given_arr= np.array([[2,3,4], [5,6,7]], dtype= int)
zeros_like_array = np.zeros_like(given_arr)
print("array of zeros = ",zeros_like_array)

# 5
one = np.ones_like(given_arr)
print("array of ones",one )

#6
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("numpy array = ",numpy_array)



Empty 2x2 array: [[2.69404964e-315 0.00000000e+000]
 [0.00000000e+000 9.88131292e-324]]
one_array = [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full_arr with fill value =  [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
array of zeros =  [[0 0 0]
 [0 0 0]]
array of ones [[1 1 1]
 [1 1 1]]
numpy array =  [1 2 3 4]


In [10]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

import numpy as np
# 1
arr1 = np.arange(10,50)
print(arr1)

# 2

arr1 = np.arange(0,9)
arr2 = arr1.reshape(3,3)
print(arr1)
print(arr2)

# 3

Identity_matrix = np.eye(3)
print(Identity_matrix)

# 4

arr1 = np.random.random(30)
meanOfArr1 = arr1.mean()
print(meanOfArr1)

# 5

arr1 = np.random.randint(1,200,100)
arr2 = arr1.reshape(10,10)
print(arr2)

max = np.max(arr2)
min = np.min(arr2)
print(max)
print(min)

# 6

arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
print(arr1)

# 7

arr = np.array([1,2,0,0,4,0])
arr1 = arr[::-1]
print(arr1)

# 8

n = 5
border_array = np.ones((n, n), dtype=int)
border_array[1:-1, 1:-1] = 0

print(border_array)

# 9

import numpy as np
arr = np.ones((8,8))
arr[1::2,::2] = 0
arr[::2,1::2] = 0

print(arr)





[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.5192816755398749
[[ 13 136  17  50  90  84  24 171  78 159]
 [ 57 145  88 196 113  88 107 102 161  96]
 [175  76 131 145 104  93  59 180  55 179]
 [129 196  44 198 181 188 165  83  38  14]
 [ 66 163  90  58 166   3  19  91  36 194]
 [ 45 129 172  55  83 165 145 128  90  44]
 [186  20 167 160  36 128 100 158 106 192]
 [110 187  93  82 172  77 109 169 181 135]
 [103  63  61  47  84 114 151  45 186 124]
 [124 120 117  53  47  23  53  43  70  13]]
198
3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0

In [21]:
# Problem - 3: Array Operations:

import numpy as np

x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6],
              [7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1

print("Add of x and y: ",np.add(x,y))
print("Add  of v and w: ",np.add(v,w))

# 2

print("Subtract of y from x: ",np.subtract(x,y))
print("Subtract of  w from v: ",np.subtract(v,w))

# 3

print("Multiplying x by 3: ",np.multiply(x,3))
print("Multiplying y by 2: ",np.multiply(y,2))
print("Multiplying v by 5: ",np.multiply(v,5))
print("Multiplying w by 4: ",np.multiply(w,4))

# 4
print("Square of x =\n", x ** 2)
print("Square of y =\n", y ** 2)
print("Square of v =\n", v ** 2)
print("Square of w =\n", w ** 2)

# 5
print("The dot product between v and w is ", np.dot(v,w))
print("The dot product between x and v is ", np.dot(x,v))
print("The dot product between x and y is ", np.dot(x,y))

# 6

np.concatenate((x, v))
# all the input arrays must have same number of dimensions,  but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)





Add of x and y:  [[ 6  8]
 [10 13]]
Add  of v and w:  [20 22]
Subtract of y from x:  [[-4 -4]
 [-4 -3]]
Subtract of  w from v:  [-2 -2]
Multiplying x by 3:  [[ 3  6]
 [ 9 15]]
Multiplying y by 2:  [[10 12]
 [14 16]]
Multiplying v by 5:  [45 50]
Multiplying w by 4:  [44 48]
Square of x =
 [[ 1  4]
 [ 9 25]]
Square of y =
 [[25 36]
 [49 64]]
Square of v =
 [ 81 100]
Square of w =
 [121 144]
The dot product between v and w is  219
The dot product between x and v is  [29 77]
The dot product between x and y is  [[19 22]
 [50 58]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [26]:
# 4: Matrix Operations:

# 1 Prove A.A−1 = I.

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Inverse = np.linalg.inv(A)
print(Inverse)
product = np.dot(A,Inverse)
print(np.round(product,10))

# 2 Prove AB ̸= BA.

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

ab = np.dot(A,B)
ba = np.dot(B,A)
if(np.array_equal(ab,ba)):
  print("AB is equal to BA")
else:
  print("AB is not equal to BA")

# 3 Prove (AB)T = BTAT.

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

ab = np.dot(A,B)
abTranspose = ab.T

bTranspose = B.T
aTranspose = A.T

dotBtAt = np.dot(bTranspose,aTranspose)

if(np.array_equal(abTranspose,dotBtAt)):
    print(True)

''' 4 Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
'''

A = np.array([[2,-3,1],
             [1,-1,2],
             [3,1,-1]])
B = np.array([[-1],
             [-3],
             [9]])

A_Inverse = np.linalg.inv(A)
X = np.dot(A_Inverse,B)
print(X)






[[-2.    1.  ]
 [ 1.75 -0.75]]
[[1. 0.]
 [0. 1.]]
AB is not equal to BA
True
[[ 2.]
 [ 1.]
 [-2.]]
